# This script recode survey data for
# "Voting Experiences, Perceptions of Fraud, and Voter Confidence" (R. Michael Alvarez, Jian Cao, and Yimeng Li).
# !!! Note: This script needs to be opened with UTF-8 encoding. 
# For questions regarding this code, contact Yimeng Li.
# Date: Jan 23, 2021.

# Set working directory:
setwd("C:/OneDrive - California Institute of Technology/Empirical - Voter Confidence")

# Load libraries:
library(dplyr)
library(mgsub)
library(stringr)
library(survey)

# Load dataset:
load("E:/OC Survey/Data/OCvoters_design_confidence.rda")

OCsurvey_design <- svydesign(ids = ~1, probs = as.double(OCsurvey_design$prob), data = OCsurvey_design$variables)

OCsurvey_design$variables <- OCsurvey_design$variables %>%
  transmute(
    id = rownames(.),
    birth_year = case_when(ResponseId == "R_9RFQv4O1xzlKJPj" ~ "1945",
                           Q12 == "0000" ~ NA_character_,
                           Q12 == "05/0155" ~ "1955",
                           Q12 == "1034" ~ "1934",
                           Q12 == "1056" ~ "1956",
                           Q12 == "1085" ~ "1985",
                           Q12 == "1836" ~ "1936",
                           Q12 == "1845" ~ "1945",
                           Q12 == "1868" ~ "1968",
                           Q12 == "2018" ~ NA_character_,
                           Q12 == "2952" ~ "1952",
                           Q12 == "57" ~ "1957",
                           Q12 == "before 1965" ~ NA_character_,
                           Q12 == "none of your business" ~ NA_character_,
                           Q12 == "Xxxx" ~ NA_character_,
                           TRUE ~ Q12),
    age = if_else(as.numeric(str_sub(birth_year, start = -4)) >= 1900 &
                    as.numeric(str_sub(birth_year, start = -4)) <= 2000,
                  2018 - as.numeric(str_sub(birth_year, start = -4)), NA_real_),
    age = case_when(age <= 29 ~ "Below 30",
                    age <= 44 ~ "30-44",
                    age <= 64 ~ "45-64",
                    age <= 120 ~ "65 or above",
                    TRUE ~ NA_character_),
    age = factor(age, levels = c("Below 30", "30-44", "45-64", "65 or above")),
    
    gender = case_when(Q14 %in% c("Prefer not to say", "Self-describe") ~ NA_character_,
                       TRUE ~ Q14),
    female = if_else(gender == "Female", 1, 0),
    
    educ = case_when(Q16 %in% c("Did not graduate from high school", "High school graduate") ~ "High school or less",
                     TRUE ~ Q16),
    educ = factor(educ, levels = c("High school or less", "Some college, but no degree (yet)", "2-year college degree",
                                   "4-year college degree", "Postgraduate degree (MA, MBA, MD, JD, PhD, etc.)")),
    
    first_time = case_when(Q38 == "I am a first time voter" ~ 1,
                           Q38 == "I have voted in elections before" ~ 0,
                           TRUE ~ NA_real_),
    
    mode = case_when(Q40 %in% c("Voted in person on Election Day (at a polling place or precinct)",
                                "Voted in person before Election Day") ~ "In person",
                     Q40 == "Voted by mail or absentee ballot by mail" ~ "By mail"),
    in_person = if_else(mode == "In person", 1, 0),
    
    poll_finding = case_when(Q51 == "Very difficult" | Q52 == "Very difficult" ~ "Very difficult",
                             Q51 == "Somewhat difficult" | Q52 == "Somewhat difficult" ~ "Somewhat difficult",
                             Q51 == "Fairly easy" | Q52 == "Fairly easy" ~ "Fairly easy",
                             Q51 == "Very easy" | Q52 == "Very easy" ~ "Very easy",
                             Q51 == "I don't know" | Q52 == "I don't know" ~ "I don't know",
                             TRUE ~ NA_character_),
    poll_finding_difficult = case_when(poll_finding %in% c("Very difficult", "Somewhat difficult") ~ 1,
                                       poll_finding %in% c("Fairly easy", "Very easy") ~ 0,
                                       TRUE ~ NA_real_),
    
    reg_problem = case_when(Q59 == "Yes (please specify what problem, or problems, you had below)" ~ 1,
                            Q59 == "No" ~ 0,
                            TRUE ~ NA_real_),
    
    poll_closed = case_when(Q63 == "It was open" ~ 0,
                            Q63 == "It was closed" ~ 1,
                            TRUE ~ NA_real_),
    
    wait_time = case_when(Q67 == "Not at all" ~ "Not at all",
                          Q67 == "Less than 10 minutes" ~ "Less than 10 minutes",
                          Q67 == "10-30 minutes" ~ "10-30 minutes",
                          Q67 == "31 minutes - 1 hour" ~ "31 minutes - 1 hour",
                          Q67 == "More than 1 hour (please specify how long below)" ~ "More than 1 hour",
                          Q67 == "I don't know" ~ "I don't know",
                          TRUE ~ NA_character_),
    wait_time_long = case_when(wait_time %in% c("31 minutes - 1 hour", "More than 1 hour") ~ 1,
                               wait_time %in% c("Not at all", "Less than 10 minutes", "10-30 minutes") ~ 0,
                               TRUE ~ NA_real_),
    
    equip_problem = case_when(Q71 == "Yes (please specify what problem, or problems, you had below)" ~ 1,
                              Q71 == "No" ~ 0,
                              TRUE ~ NA_real_),
    
    pollworker_rating = case_when(Q73 == "Excellent" | Q74 == "Excellent" ~ "Excellent",
                                  Q73 == "Good" | Q74 == "Good" ~ "Good",
                                  Q73 == "Fair" | Q74 == "Fair" ~ "Fair",
                                  Q73 == "Poor" | Q74 == "Poor" ~ "Poor",
                                  Q73 == "I don't know" | Q74 == "I don't know" ~ "I don't know",
                                  TRUE ~ NA_character_),
    pollworker_rating_poor = case_when(pollworker_rating == "Poor" ~ 1,
                                       pollworker_rating %in% c("Excellent", "Good", "Fair") ~ 0,
                                       TRUE ~ NA_real_),
    
    pollworker_color = case_when(Q76 %in% c("Asian", "Other/multi-racial", "Hispanic", "African-American", "Native American") ~ 1,
                                 Q76 == "White" ~ 0,
                                 TRUE ~ NA_real_),
    
    pollworker_old   = case_when(Q78 %in% c("Between 51 and 70", "Older than 70") ~ 1,
                                 Q78 %in% c("Under 30", "Between 31 and 50") ~ 0,
                                 TRUE ~ NA_real_),
    
    absentee_get_problem =  case_when(Q82 == "Yes (please specify what problem, or problems, you had below)" ~ 1,
                                      Q82 == "No" ~ 0,
                                      TRUE ~ NA_real_),
    
    absentee_mark_problem = case_when(Q84 == "Yes (please specify what problem, or problems, you had below)" ~ 1,
                                      Q84 == "No" ~ 0,
                                      TRUE ~ NA_real_),
    
    return_location = suppressWarnings(as.numeric(unlist(mgsub(Q90,
                                                               c("Post office box at a U.S. Postal Service location",
                                                                 "Official post office box not at a U.S. Postal Service location",
                                                                 "Picked up by the postal worker who delivers mail to my home",
                                                                 "Main election office",
                                                                 "Voting center, not a neighborhood polling place",
                                                                 "Other \\(please specify below)",
                                                                 "Neighborhood polling place",
                                                                 "I don't know",
                                                                 "Drop box used only for ballots, not located at an election office or polling place"),
                                                               c(1, 2, 3, 5, 7, 8, 6, 9, 4))))),
    
    return_location_text = suppressWarnings(as.numeric(unlist(mgsub(Q90_8_TEXT,
                                                                    c("Picked up by postal worker at workplace",
                                                                      "Irvine City Hall drop box",
                                                                      "Fax",
                                                                      "Outgoing mail at work",
                                                                      "Dropped off at workplace mailroom",
                                                                      "Ballot was never received",
                                                                      "my husband dropped it off when he went to vote in person",
                                                                      "Bought a stamp and let the post master take it.",
                                                                      "Priority Mail",
                                                                      "Dorm mail service",
                                                                      "outgoing mail slot at apartment complex",
                                                                      "I handed by ballot envelope \\(w/postage) to a post office employee for mailing.",
                                                                      "Didn¡¯t receive it, to return it.",
                                                                      "Office mail box drop",
                                                                      "Post office on Warner",
                                                                      "Not returned, never received a ballot.",
                                                                      "Mailed in outgoing mail from work",
                                                                      "Picked up by a postal worker from my place of work",
                                                                      "Postal Annex",
                                                                      "My workplace mailroom",
                                                                      "Postal center",
                                                                      "Office mail room",
                                                                      "Mailed at work",
                                                                      "Group mailbox slot on my street",
                                                                      "I never received my ballot.",
                                                                      "I am in Mexico and a local business returned my ballot for me.",
                                                                      "fax machine",
                                                                      "UPS store",
                                                                      "Put in mail at work",
                                                                      "Fax machine at the registrar of voters",
                                                                      "Candidates Election Office",
                                                                      "by fax",
                                                                      "Picked up by postal worker at my place of employment",
                                                                      "Irvine civic center 1 week before the election",
                                                                      "Foreign Post Office",
                                                                      "UCI polling center",
                                                                      "I never received it.",
                                                                      "Window at post office",
                                                                      "Mailed back by my employers mail center",
                                                                      "Someone on mike levin¡¯s campaign picked it up from my house and returned it to a voting center for me.",
                                                                      "Faxed! Need to add this to your absentee ballot Options!",
                                                                      "College Out-going Mailbox",
                                                                      "Mailed from work",
                                                                      "Campaign official",
                                                                      "Sent registered mail at post office",
                                                                      "Congressional office mailing system.",
                                                                      "Post office",
                                                                      "no where, I never received a ballot",
                                                                      "Electronic",
                                                                      "faxed ballot",
                                                                      "Post office box in London, UK",
                                                                      "picked up by postal worker at my work place",
                                                                      "Irvine city center, don¡¯t know if it was a voting center or polling place",
                                                                      "Work mailbox",
                                                                      "office outgoing mail",
                                                                      "I can't return a ballot that never came! My absentee ballot never came!",
                                                                      "Never got it.",
                                                                      "It never got returned because I couldn't send it. Y'all got some work to do on this survey. Didn't get the ballot, couldn't send back what I couldn't even mark bc I didn't have it.",
                                                                      "At USPS counter; mailed certified (tracking number: 70180680000060501965)",
                                                                      "'@ PO Box but I wanted to do drop off but it closed too early in the day",
                                                                      "Foreign Post Office Box",
                                                                      "City Hall",
                                                                      "Gave to USPS person at Post Office",
                                                                      "Foreign postal service",
                                                                      "Mailed from my office",
                                                                      "Personally handed to my regular P.O. carrier",
                                                                      "Gave to postman who was delivering in business district.  I could not find the P.O. or a postal drop box  which was my original intent.",
                                                                      "college mail room, picked up by the US postal service",
                                                                      "Voting polling place",
                                                                      "Mailbox a block away-drop off",
                                                                      "Mission Viejo early voting ballot drop off",
                                                                      "It was no returned because the stamp date deadline passed.",
                                                                      "Went to post office",
                                                                      "Mailbox at my offices business park",
                                                                      "Not applicable",
                                                                      "OC Registrar of Voters",
                                                                      "at local middle school",
                                                                      "Mailbox in Office",
                                                                      "Post Office",
                                                                      "Hand delivered to postal clerk at post office",
                                                                      "Picked up by postal worker who delivers at my place of employment",
                                                                      "German Post office box",
                                                                      "At the poll where I was working.",
                                                                      "Picked up by postal work at work",
                                                                      "Polling place",
                                                                      "Registrar",
                                                                      "Mail box at my place of employment",
                                                                      "dropped it off at work outgoing mail bin.",
                                                                      "By Fax from foreign country",
                                                                      "Work mail box",
                                                                      "Tried by email to registrar but not delivered.",
                                                                      "I dropped it off at my college's mail center.",
                                                                      "Mail Drop Box at My Office",
                                                                      "school",
                                                                      "Ballot with fax cover sheet was faxed to  fax@fvap.gov  for them to fax it on to the OC election board.",
                                                                      "office mail",
                                                                      "Apartment Complex mail box",
                                                                      "Outgoing mail box at work",
                                                                      "Public mailbox",
                                                                      "Polling place I was working at",
                                                                      "I was working as a canvasser for a race, so I brought it to our field office. Someone at the office turned it in, along with other ballots that us canvassers collected from people at their homes (probably they drove it to the registrars office? Or drove it to a polling place?)",
                                                                      "Office mail pickup",
                                                                      "Tried to fax, but couldn't get through so had to email scanned copy to FVAP",
                                                                      "I gave it to the hotel staff",
                                                                      "Handed to a poll worker at a polling place.",
                                                                      "Mailroom at my office",
                                                                      "Office mail.",
                                                                      "I had requested an address change, then my ballot was returned, luckily I checked out line and saw it was return, if they would have checked they would have had enough time to resend",
                                                                      "Personally gave it to my mail carrier",
                                                                      "USPS Pick-up from work",
                                                                      "I did not get to send it back because I never had it to begin with.",
                                                                      "Picked up from my workplace by USPS",
                                                                      "On campus mail location",
                                                                      "My ballot was not received, so it could not be returned",
                                                                      "Hand delivered by me to the u.s. postal office desk worker",
                                                                      "My mom¡¯s school mail person",
                                                                      "I didn't return my vote, but there is no option for this in the last couple questions.",
                                                                      "a community box for out-going mail",
                                                                      "A school",
                                                                      "UPS Store",
                                                                      "In the ballot box At my polling place",
                                                                      "By a postal worker who picked up from our work office",
                                                                      "Fax due to overseas",
                                                                      "O.C. Registrar's drop box",
                                                                      "Handed to postal worker in post office, watched as it was hand-cancelled.",
                                                                      "ballot wasn't returned.",
                                                                      "mail out",
                                                                      "Work, post office picked it up",
                                                                      "email for overseas voters",
                                                                      "Mail box at work",
                                                                      "Early voting mobil voting booth.",
                                                                      "na",
                                                                      "Irvine City Hall Drive-Through ballot return service",
                                                                      "Irvine Civic Center",
                                                                      "Handed the ballot directly to the postal worker when he delivered our mail.",
                                                                      "Never received - not returned",
                                                                      "Office mail drop",
                                                                      "Post office abroad",
                                                                      "Royal Mail post office (UK)",
                                                                      "It was faxed back. You dont have that option but fax or mail are only ways to return absentee ballots.",
                                                                      "Picked up by postal worker where I work.",
                                                                      "Ballot was not returned because I didn¡¯t receive it in the first place",
                                                                      "picked up by postal worker at spouse's office",
                                                                      "Picked up from by postal worker from my office",
                                                                      "n/a",
                                                                      "mail room at college dorm",
                                                                      "picked up at civic center",
                                                                      "Picked up at my work by the USPS",
                                                                      "Work place mail drop",
                                                                      "Mail Carrier at my work",
                                                                      "mail drop at my  work",
                                                                      "DHL courier from overseas",
                                                                      "Early Voting site.",
                                                                      "My ballot was returned via fax as I am currently out of the country",
                                                                      "Mailed from employer's mail room",
                                                                      "My mailbox",
                                                                      "Work out-going mail",
                                                                      "Where I pick up my mail",
                                                                      "OC Registrar's Office",
                                                                      "Drop off location at early voting location",
                                                                      "The UPS Store",
                                                                      "Dropped off at work mail room",
                                                                      "Drop Box at a polling place located in a school",
                                                                      "I never received a ballot",
                                                                      "Could not turn it in since it came after November 6",
                                                                      "Inside Post Office",
                                                                      "Work Mail"),
                                                                    c(3,4,7,3,3,8,5,3,3,3,3,1,8,3,1,8,3,3,3,3,1,3,3,3,8,7,7,1,
                                                                      3,7,6,7,3,7,2,6,8,1,3,7,7,3,3,7,1,2,1,8,7,6,2,3,7,3,3,8,
                                                                      8,8,1,8,2,4,1,2,3,3,3,3,6,2,7,8,1,2,8,7,7,2,1,1,3,2,6,3,
                                                                      6,7,2,3,5,3,8,3,3,7,7,3,3,3,2,6,7,3,5,3,6,3,3,3,3,3,8,3,
                                                                      2,8,1,3,8,3,7,1,6,3,5,4,1,8,3,3,5,3,7,8,4,7,3,8,3,2,2,5,
                                                                      3,8,3,3,9,3,7,3,3,3,3,2,7,5,3,3,3,3,7,7,1,3,6,8,8,1,3))))),
    
    return_usps = case_when(return_location %in% c(1,2,3) | return_location_text %in% c(1,2,3) ~ 1,
                            return_location %in% c(4,5,6,7) | return_location_text %in% c(4,5,6,7,8) ~ 0,
                            TRUE ~ NA_real_),
    
    return_early = case_when(Q100 %in% c("More than a week before Election Day", "A few days before Election Day", "The week before Election Day") ~ 1,
                             Q100 == "On Election Day" ~ 0,
                             TRUE ~ NA_real_),
    
    instruction_complexity = case_when(Q102 == "Very easy" | Q103 == "Very easy" ~ "Very easy",
                                       Q102 == "Somewhat easy" | Q103 == "Somewhat easy" ~ "Somewhat easy",
                                       Q102 == "Somewhat hard" | Q103 == "Somewhat hard" ~ "Somewhat hard",
                                       Q102 == "Very hard" | Q103 == "Very hard" ~ "Very hard",
                                       Q102 == "I don't remember" | Q103 == "I don't remember" ~ "I don't remember",
                                       TRUE ~ NA_character_),
    instruction_hard = case_when(instruction_complexity %in% c("Somewhat hard", "Very hard") ~ 1,
                                 instruction_complexity %in% c("Very easy", "Somewhat easy") ~ 0,
                                 TRUE ~ NA_real_),
    
    confidence_own = case_when(Q131 == "Very confident" | Q139 == "Very confident" | Q147_1 == "Very confident" | Q150_1  == "Very confident" ~ "Very confident",
                               Q131 == "Somewhat confident" | Q139 == "Somewhat confident" | Q147_1 == "Somewhat confident" | Q150_1  == "Somewhat confident" ~ "Somewhat confident",
                               Q131 == "Not too confident" | Q139 == "Not too confident" | Q147_1 == "Not too confident" | Q150_1  == "Not too confident" ~ "Not too confident",
                               Q131 == "Not at all confident" | Q139 == "Not at all confident" | Q147_1 == "Not at all confident" | Q150_1  == "Not at all confident" ~ "Not at all confident",
                               Q131 == "I don't know" | Q139 == "I don't know" | Q147_1 == "I don't know" | Q150_1  == "I don't know" ~ "I don't know",
                               TRUE ~ NA_character_),
    
    confidence_OC = case_when(Q133 == "Very confident" | Q141 == "Very confident" | Q147_2 == "Very confident" | Q150_2  == "Very confident" | Q148_1 == "Very confident" | Q151_1  == "Very confident" ~ "Very confident",
                              Q133 == "Somewhat confident" | Q141 == "Somewhat confident" | Q147_2 == "Somewhat confident" | Q150_2  == "Somewhat confident" | Q148_1 == "Somewhat confident" | Q151_1  == "Somewhat confident" ~ "Somewhat confident",
                              Q133 == "Not too confident" | Q141 == "Not too confident" | Q147_2 == "Not too confident" | Q150_2  == "Not too confident" | Q148_1 == "Not too confident" | Q151_1  == "Not too confident" ~ "Not too confident",
                              Q133 == "Not at all confident" | Q141 == "Not at all confident" | Q147_2 == "Not at all confident" | Q150_2  == "Not at all confident" | Q148_1 == "Not at all confident" | Q151_1  == "Not at all confident" ~ "Not at all confident",
                              Q133 == "I don't know" | Q141 == "I don't know" | Q147_2 == "I don't know" | Q150_2  == "I don't know" | Q148_1 == "I don't know" | Q151_1  == "I don't know" ~ "I don't know",
                              TRUE ~ NA_character_),
    
    confidence_CA = case_when(Q135 == "Very confident" | Q143 == "Very confident" | Q147_3 == "Very confident" | Q150_3  == "Very confident" | Q148_2 == "Very confident" | Q151_2  == "Very confident" ~ "Very confident",
                              Q135 == "Somewhat confident" | Q143 == "Somewhat confident" | Q147_3 == "Somewhat confident" | Q150_3  == "Somewhat confident" | Q148_2 == "Somewhat confident" | Q151_2  == "Somewhat confident" ~ "Somewhat confident",
                              Q135 == "Not too confident" | Q143 == "Not too confident" | Q147_3 == "Not too confident" | Q150_3  == "Not too confident" | Q148_2 == "Not too confident" | Q151_2  == "Not too confident" ~ "Not too confident",
                              Q135 == "Not at all confident" | Q143 == "Not at all confident" | Q147_3 == "Not at all confident" | Q150_3  == "Not at all confident" | Q148_2 == "Not at all confident" | Q151_2  == "Not at all confident" ~ "Not at all confident",
                              Q135 == "I don't know" | Q143 == "I don't know" | Q147_3 == "I don't know" | Q150_3  == "I don't know" | Q148_2 == "I don't know" | Q151_2  == "I don't know" ~ "I don't know",
                              TRUE ~ NA_character_),
    
    confidence_US = case_when(Q137 == "Very confident" | Q145 == "Very confident" | Q147_4 == "Very confident" | Q150_4  == "Very confident" | Q148_3 == "Very confident" | Q151_3  == "Very confident" ~ "Very confident",
                              Q137 == "Somewhat confident" | Q145 == "Somewhat confident" | Q147_4 == "Somewhat confident" | Q150_4  == "Somewhat confident" | Q148_3 == "Somewhat confident" | Q151_3  == "Somewhat confident" ~ "Somewhat confident",
                              Q137 == "Not too confident" | Q145 == "Not too confident" | Q147_4 == "Not too confident" | Q150_4  == "Not too confident" | Q148_3 == "Not too confident" | Q151_3  == "Not too confident" ~ "Not too confident",
                              Q137 == "Not at all confident" | Q145 == "Not at all confident" | Q147_4 == "Not at all confident" | Q150_4  == "Not at all confident" | Q148_3 == "Not at all confident" | Q151_3  == "Not at all confident" ~ "Not at all confident",
                              Q137 == "I don't know" | Q145 == "I don't know" | Q147_4 == "I don't know" | Q150_4  == "I don't know" | Q148_3 == "I don't know" | Q151_3  == "I don't know" ~ "I don't know",
                              TRUE ~ NA_character_),
    
    confidence_own_o = case_when(confidence_own == "I don't know" ~ NA_real_,
                                 confidence_own == "Not at all confident" ~ 1,
                                 confidence_own == "Not too confident" ~ 2,
                                 confidence_own == "Somewhat confident" ~ 3,
                                 confidence_own == "Very confident" ~ 4,
                                 TRUE ~ NA_real_),
    
    confidence_own_b = case_when(confidence_own_o %in% c(3, 4) ~ 1,
                                 confidence_own_o %in% c(1, 2) ~ 0,
                                 TRUE ~ NA_real_),
    
    confidence_OC_o = case_when(confidence_OC == "I don't know" ~ NA_real_,
                                confidence_OC == "Not at all confident" ~ 1,
                                confidence_OC == "Not too confident" ~ 2,
                                confidence_OC == "Somewhat confident" ~ 3,
                                confidence_OC == "Very confident" ~ 4,
                                TRUE ~ NA_real_),
    
    confidence_OC_b = case_when(confidence_OC_o %in% c(3, 4) ~ 1,
                                confidence_OC_o %in% c(1, 2) ~ 0,
                                TRUE ~ NA_real_),
    
    confidence_CA_o = case_when(confidence_CA == "I don't know" ~ NA_real_,
                                confidence_CA == "Not at all confident" ~ 1,
                                confidence_CA == "Not too confident" ~ 2,
                                confidence_CA == "Somewhat confident" ~ 3,
                                confidence_CA == "Very confident" ~ 4,
                                TRUE ~ NA_real_),
    
    confidence_CA_b = case_when(confidence_CA_o %in% c(3, 4) ~ 1,
                                confidence_CA_o %in% c(1, 2) ~ 0,
                                TRUE ~ NA_real_),
    
    confidence_US_o = case_when(confidence_US == "I don't know" ~ NA_real_,
                                confidence_US == "Not at all confident" ~ 1,
                                confidence_US == "Not too confident" ~ 2,
                                confidence_US == "Somewhat confident" ~ 3,
                                confidence_US == "Very confident" ~ 4,
                                TRUE ~ NA_real_),
    
    confidence_US_b = case_when(confidence_US_o %in% c(3, 4) ~ 1,
                                confidence_US_o %in% c(1, 2) ~ 0,
                                TRUE ~ NA_real_),
    
    fraud_1 = case_when(Q153_1 == "It is very common" | Q154_1 == "It is very common" ~ "It is very common",
                        Q153_1 == "It occurs occasionally" | Q154_1 == "It occurs occasionally" ~ "It occurs occasionally",
                        Q153_1 == "It occurs infrequently" | Q154_1 == "It occurs infrequently" ~ "It occurs infrequently",
                        Q153_1 == "It almost never occurs" | Q154_1 == "It almost never occurs" ~ "It almost never occurs",
                        Q153_1 == "I’m not sure" | Q154_1 == "I’m not sure" ~ "I'm not sure",
                        TRUE ~ NA_character_),
    
    fraud_2 = case_when(Q153_2 == "It is very common" | Q154_2 == "It is very common" ~ "It is very common",
                        Q153_2 == "It occurs occasionally" | Q154_2 == "It occurs occasionally" ~ "It occurs occasionally",
                        Q153_2 == "It occurs infrequently" | Q154_2 == "It occurs infrequently" ~ "It occurs infrequently",
                        Q153_2 == "It almost never occurs" | Q154_2 == "It almost never occurs" ~ "It almost never occurs",
                        Q153_2 == "I’m not sure" | Q154_2 == "I’m not sure" ~ "I'm not sure",
                        TRUE ~ NA_character_),
    
    fraud_3 = case_when(Q153_3 == "It is very common" | Q154_3 == "It is very common" ~ "It is very common",
                        Q153_3 == "It occurs occasionally" | Q154_3 == "It occurs occasionally" ~ "It occurs occasionally",
                        Q153_3 == "It occurs infrequently" | Q154_3 == "It occurs infrequently" ~ "It occurs infrequently",
                        Q153_3 == "It almost never occurs" | Q154_3 == "It almost never occurs" ~ "It almost never occurs",
                        Q153_3 == "I’m not sure" | Q154_3 == "I’m not sure" ~ "I'm not sure",
                        TRUE ~ NA_character_),
    
    fraud_4 = case_when(Q153_4 == "It is very common" | Q154_4 == "It is very common" ~ "It is very common",
                        Q153_4 == "It occurs occasionally" | Q154_4 == "It occurs occasionally" ~ "It occurs occasionally",
                        Q153_4 == "It occurs infrequently" | Q154_4 == "It occurs infrequently" ~ "It occurs infrequently",
                        Q153_4 == "It almost never occurs" | Q154_4 == "It almost never occurs" ~ "It almost never occurs",
                        Q153_4 == "I’m not sure" | Q154_4 == "I’m not sure" ~ "I'm not sure",
                        TRUE ~ NA_character_),
    
    fraud_5 = case_when(Q153_5 == "It is very common" | Q154_5 == "It is very common" ~ "It is very common",
                        Q153_5 == "It occurs occasionally" | Q154_5 == "It occurs occasionally" ~ "It occurs occasionally",
                        Q153_5 == "It occurs infrequently" | Q154_5 == "It occurs infrequently" ~ "It occurs infrequently",
                        Q153_5 == "It almost never occurs" | Q154_5 == "It almost never occurs" ~ "It almost never occurs",
                        Q153_5 == "I’m not sure" | Q154_5 == "I’m not sure" ~ "I'm not sure",
                        TRUE ~ NA_character_),
    
    fraud_6 = case_when(Q153_6 == "It is very common" | Q154_6 == "It is very common" ~ "It is very common",
                        Q153_6 == "It occurs occasionally" | Q154_6 == "It occurs occasionally" ~ "It occurs occasionally",
                        Q153_6 == "It occurs infrequently" | Q154_6 == "It occurs infrequently" ~ "It occurs infrequently",
                        Q153_6 == "It almost never occurs" | Q154_6 == "It almost never occurs" ~ "It almost never occurs",
                        Q153_6 == "I’m not sure" | Q154_6 == "I’m not sure" ~ "I'm not sure",
                        TRUE ~ NA_character_),
    
    fraud_1_common = case_when(fraud_1 %in% c("It is very common", "It occurs occasionally") ~ "Yes",
                               fraud_1 %in% c("It occurs infrequently", "It almost never occurs") ~ "No",
                               fraud_1 == "I'm not sure" ~ "Not sure",
                               TRUE ~ NA_character_),
    
    fraud_2_common = case_when(fraud_2 %in% c("It is very common", "It occurs occasionally") ~ "Yes",
                               fraud_2 %in% c("It occurs infrequently", "It almost never occurs") ~ "No",
                               fraud_2 == "I'm not sure" ~ "Not sure",
                               TRUE ~ NA_character_),
    
    fraud_3_common = case_when(fraud_3 %in% c("It is very common", "It occurs occasionally") ~ "Yes",
                               fraud_3 %in% c("It occurs infrequently", "It almost never occurs") ~ "No",
                               fraud_3 == "I'm not sure" ~ "Not sure",
                               TRUE ~ NA_character_),
    
    fraud_4_common = case_when(fraud_4 %in% c("It is very common", "It occurs occasionally") ~ "Yes",
                               fraud_4 %in% c("It occurs infrequently", "It almost never occurs") ~ "No",
                               fraud_4 == "I'm not sure" ~ "Not sure",
                               TRUE ~ NA_character_),
    
    fraud_5_common = case_when(fraud_5 %in% c("It is very common", "It occurs occasionally") ~ "Yes",
                               fraud_5 %in% c("It occurs infrequently", "It almost never occurs") ~ "No",
                               fraud_5 == "I'm not sure" ~ "Not sure",
                               TRUE ~ NA_character_),
    
    fraud_6_common = case_when(fraud_6 %in% c("It is very common", "It occurs occasionally") ~ "Yes",
                               fraud_6 %in% c("It occurs infrequently", "It almost never occurs") ~ "No",
                               fraud_6 == "I'm not sure" ~ "Not sure",
                               TRUE ~ NA_character_),
    
    fraud_1_common = factor(fraud_1_common, levels = c("No", "Yes", "Not sure")),
    
    fraud_2_common = factor(fraud_2_common, levels = c("No", "Yes", "Not sure")),
    
    fraud_3_common = factor(fraud_3_common, levels = c("No", "Yes", "Not sure")),
    
    fraud_4_common = factor(fraud_4_common, levels = c("No", "Yes", "Not sure")),
    
    fraud_5_common = factor(fraud_5_common, levels = c("No", "Yes", "Not sure")),
    
    fraud_6_common = factor(fraud_6_common, levels = c("No", "Yes", "Not sure")),
    
    hacking_nationwide = case_when(Q156 == "Major problem" | Q160 == "Major problem" ~ "Major problem",
                                   Q156 == "Minor problem" | Q160 == "Minor problem" ~ "Minor problem",
                                   Q156 == "Not a problem at all" | Q160 == "Not a problem at all" ~ "Not a problem at all",
                                   Q156 == "I’m not sure" | Q160 == "I’m not sure" ~ "I'm not sure",
                                   TRUE ~ NA_character_),
    
    hacking_locally = case_when(Q158 == "Major problem" | Q162 == "Major problem" ~ "Major problem",
                                Q158 == "Minor problem" | Q162 == "Minor problem" ~ "Minor problem",
                                Q158 == "Not a problem at all" | Q162 == "Not a problem at all" ~ "Not a problem at all",
                                Q158 == "I’m not sure" | Q162 == "I’m not sure" ~ "I'm not sure",
                                TRUE ~ NA_character_),
    
    hacking_nationwide_issue = case_when(hacking_nationwide %in% c("Major problem", "Minor problem") ~ "Yes",
                                         hacking_nationwide == "Not a problem at all" ~ "No",
                                         hacking_nationwide == "I'm not sure" ~ "Not sure",
                                         TRUE ~ NA_character_),
    
    hacking_nationwide_issue = factor(hacking_nationwide_issue, levels = c("No", "Yes", "Not sure")),
    
    hacking_locally_issue = case_when(hacking_locally %in% c("Major problem", "Minor problem") ~ "Yes",
                                      hacking_locally == "Not a problem at all" ~ "No",
                                      hacking_locally == "I'm not sure" ~ "Not sure",
                                      TRUE ~ NA_character_),
    
    hacking_locally_issue = factor(hacking_locally_issue, levels = c("No", "Yes", "Not sure")),
    
    use_twitter = case_when(Q164 == "Yes" ~ 1,
                            Q164 == "No" ~ 0,
                            TRUE ~ 0),
    
    twitter_discuss_neg = case_when(Q166 %in% c("Yes, my negative experiences", "Yes, both positive and negative experiences") ~ 1,
                                    Q166 %in% c("Yes, my positive experiences", "No") ~ 0,
                                    use_twitter == 0 ~ 0,
                                    TRUE ~ NA_real_),
    
    discuss_concerns = case_when(Q172 == "Yes" ~ 1,
                                 Q172 == "No" ~ 0,
                                 use_twitter == 0 ~ 0,
                                 TRUE ~ NA_real_),
    
    receive_concerns = case_when(Q174 == "Yes" ~ 1,
                                 Q174 == "No" ~ 0,
                                 use_twitter == 0 ~ 0,
                                 TRUE ~ NA_real_),
    
    follow_news = case_when(Q189 %in% c("Hardly at all", "Only now and then") ~ "Not often",
                            TRUE ~ Q189),
    
    follow_news = factor(follow_news, levels = c("Not often", "Some of the time", "Most of the time")),
    
    race = case_when(Q193 == "Yes" ~ "Hispanic",
                     Q191 == "White" ~ "White",
                     Q191 == "Hispanic or Latino" ~ "Hispanic",
                     Q191 == "Asian or Asian American" ~ "Asian",
                     Q191 %in% c("Black or African American", "Middle Eastern", "Native American", " 2 or more races", "Other") ~ "Other races",
                     TRUE ~ NA_character_),
    
    race_factor = factor(race, levels = c("White", "Hispanic", "Asian", "Other races")),
    
    marital = case_when(Q195 %in% c("Married", "Living with partner") ~ 1,
                        Q195 %in% c("Widowed", "Divorced", "Separated", "Never married") ~ 0,
                        TRUE ~ NA_real_),
    
    homeowner = case_when(Q197 == "Own (by me or someone in my household)" ~ 1,
                          Q197 %in% c("Rent (by me or someone in my household)", "Occupy without paying rent") ~ 0,
                          TRUE ~ NA_real_),
    
    income = case_when(Q202 %in% c("Less than $5,000", "$5,000 to $7,499", "$7,500 to $9,999", "$10,000 to $12,499",
                                   "$12,500 to $14,999", "$15,000 to $19,999", "$20,000 to $24,999", "$25,000 to $29,999",
                                   "$30,000 to $34,999", "$35,000 to $39,999", "$40,000 to $49,999", "$50,000 to $59,999",
                                   "$60,000 to $74,999") ~ "Less than $75,000",
                       Q202 %in% c("$75,000 to $84,999", "$85,000 to $99,999", "$100,000 to $124,999") ~ "$75,000 to $124,999",
                       Q202 %in% c("$125,000 to $149,999", "$150,000 to $174,999") ~ "$125,000 to $174,999",
                       Q202 == "$175,000 or more" ~ "$175,000 or more",
                       TRUE ~ NA_character_),
    
    income = factor(income, levels = c("Less than $75,000", "$75,000 to $124,999", "$125,000 to $174,999", "$175,000 or more")),
    
    congressional_district = szDistrictName_1,
    
    party_registration = party_factor,
    
    permanent_absentee_status = as.numeric(PAV_factor)
  ) %>%
  select(id, age, female, educ, first_time, mode, in_person,
         poll_finding_difficult, reg_problem, poll_closed, wait_time_long, equip_problem, pollworker_rating_poor, pollworker_color, pollworker_old,
         absentee_get_problem, absentee_mark_problem, return_usps, return_early, instruction_hard,
         confidence_own, confidence_own_o, confidence_own_b, confidence_OC, confidence_OC_o, confidence_OC_b,
         confidence_CA, confidence_CA_o, confidence_CA_b, confidence_US, confidence_US_o, confidence_US_b,
         fraud_1_common, fraud_2_common, fraud_3_common, fraud_4_common, fraud_5_common, fraud_6_common, hacking_nationwide_issue, hacking_locally_issue,
         use_twitter, twitter_discuss_neg, discuss_concerns, receive_concerns,
         follow_news, race_factor, marital, homeowner, income, congressional_district, party_registration, permanent_absentee_status)

save(OCsurvey_design, file = "./Data/OCvoters_design_recoded.RData")
